os: Visual Studio 2015

environment:
  matrix:
  - Compiler: mingw
  - Compiler: vs14

#cache:
#  - C:\mingw64

install:
  - set PATH=C:\MinGW\bin;C:\MinGW\msys\1.0\bin;%PATH%
  - set CC=gcc
  - set INCLUDE=%cd%\src;..\..\..\src;%INCLUDE%

build_script:
  - ps: |
      if ($env:Compiler -eq "mingw") {
        cd ./app/convbin/gcc 
        make clean all
      }
      if ($env:Compiler -eq "vs14") {
        cd ./app/convbin/vs14
        msbuild convbin-swiftnav.sln /p:Configuration=Release
        msbuild convbin-swiftnav.sln /p:Configuration=Debug
      }

artifacts:
  - path: app\convbin\gcc\sbp2rinex*
    name: sbp2rinex_mingw

  - path: app\convbin\vs14\Debug\sbp2rinex.exe
    name: sbp2rinex_vs_debug
  
  - path: app\convbin\vs14\Release\sbp2rinex.exe
    name: sbp2rinex_vs_release

test_script:
  - ps: | 
      echo "Tests go here"
