os: Visual Studio 2015

environment:
  matrix:
  - Compiler: mingw
  - Compiler: vs14

#cache:
#  - C:\mingw64

install:
  - set PATH=C:\MinGW\bin;C:\MinGW\msys\1.0\bin;%PATH%
  - set CC=gcc
  - set INCLUDE=%cd%\src;..\..\..\src;%INCLUDE%

build_script:
  - ps: |
      if ($env:Compiler -eq "mingw") {
        cd ./app/convbin/gcc 
        make clean all
      if ($env:Compiler -eq "vs14") {
        cd ./app/convbin/vs14
        msbuild convbin-swiftnav.sln
      }

artifacts:
  - path: app\convbin\gcc\convbin_swift*
    name: convbin

test_script:
  - ps: | 
      echo "Tests go here"
